### ISSUE TITLE
Remove Mandatory Parentheses from Control Statements?

### ISSUE THREAD

**Issue by trimorphdev** [kunai-lang/kunai#2]
In [the syntax example](https://github.com/kunai-lang/kunai/blob/main/syntax.kun) the condition of `if` statements are wrapped in parentheses.

```
if (condition) {
    # ...
}
```

I personally think that parentheses are unnecessary for control statements and they just make it harder to type.  Unless you have some strange syntax (which AFAIK you don't) these parentheses should be optional :)

**Comment by jeemspace** [comment]
Thanks for the suggestion! This will be a feature of the language in the future.
I should have clarified that [syntax.kun](https://github.com/kunai-lang/kunai/blob/main/syntax.kun) is incomplete and does not have all the features I intend to add, so just keep that in mind :)
